Update: Use golangco-lint for pre-commit checking

diff --git a/.githooks/pre-commit b/.githooks/pre-commit
--- a/.githooks/pre-commit
+++ b/.githooks/pre-commit
@@ -1,11 +1,8 @@
 #!/bin/sh
 
-
-files="$(gofmt -e -l -s .)"
-
-if [ -n "$files" ]; then
-    echo "Please format following files with \"gofmt -s -w .\"" >&2
-    echo "$files" | sed "s/^/  /g"
+if [ -n "$(golangci-lint run --out-format tab)" ]; then
+    echo "Please fix golangci-lint error" >&2
+    echo 'Run "golangci-lint run" to show more information' >&2
     exit 1
 fi
 exit 0
